title: Andrea Saffirio – Senior Technical Game Designer
logo: # you can add own logo.
description: > 
  Game Designer specialised in prototype creation. My dream job is contributing to interactive experiences with passion, 
  creativity and a set of skills I have developed during my studies and side projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saffirioandrea.com" # the base hostname & protocol for your site, e.g. http://example.com
seo_image: "/assets/images/ThePainterProjectShot.PNG"
favicon: "/assets/images/FavIconFolder"

# Author Settings
author:
  name: Andrea Saffirio
  image: "/assets/images/ProfilePic.png"
  image-big: "/assets/images/profPic-Big.png"
  job: Senior Technical Game Designer
  bio: >
    Hi! I am a Technical Designer with 5+ years of experience.

    I mainly worked AAA productions: on single and multiplayer games, targeting several game systems, audiences and genres.
  email: contact@saffirioandrea.com

# Contact links
contact:
  - name: LinkedIn
    link: https://www.linkedin.com/in/andrea-saffirio-19928212b/

# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # parse markdown inside block-level HTML tag
  parse_block_html: true

permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag-page
tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

categories_sorting:
  - id: "work"
    title: "Professional Projects"
  - id: "uni"
    title: "Academic Projects"
