# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrea Saffirio Video Game Designer - Projects Portfolio
email: "saffirio.andrea@outlook.com"
description: >- # this means to ignore newlines until "baseurl:"
  Creativity, passion and ambition. I am a Game Designer, graduated at Abertay University. My work consists in planning, designing and creating video games.
keywords: >- # this means to ignore newlines until "baseurl:"
  Game, Design, Andrea, Saffirio, Development, Video, Games, Production, Interactive, Indie
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://saffirioandrea.github.io" # the base hostname & protocol for your site, e.g. http://example.com
social:
  twitter:  andremcsaff
  linkedin: https://www.linkedin.com/in/andrea-saffirio-19928212b/
seo_image: "/assets/images/ThePainterProjectShot.PNG"
favicon: "/assets/images/FavIconFolder"

authors:
  use_image: true
  name: Saffirio Andrea
  image: "https://picsum.photos/400/400?image=1005"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
